---
- name: Déployer le site CV avec Docker
  hosts: localhost
  become: yes

  vars:
    app_dir: "/home/ubuntu/lyes-cv-site"
    repo_url: "https://github.com/lyesdev-oss/autodeploy-with-ansible-cv-website-FR.git"
    docker_image: "lyes-cv-site"
    docker_container: "cv-web"

  tasks:
  - name: Vérifier si Docker est installé
  command: which docker
  register: docker_path
  ignore_errors: yes

- name: Installer Docker s'il n'est pas présent
  apt:
    name: docker.io
    state: present
    update_cache: yes
    - name: Cloner/Maj dépôt CV
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Construire l'image Docker CV
      docker_image:
        path: "{{ app_dir }}"
        name: "{{ docker_image }}"
        force_source: yes
        force_tag: yes

    - name: Arrêter et supprimer ancien container si existe
      docker_container:
        name: "{{ docker_container }}"
        state: absent

    - name: Lancer et exposer le nouveau container CV
      docker_container:
        name: "{{ docker_container }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        ports:
          - "80:80"
